# Generated by Django 3.2.4 on 2021-06-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='uniqueId',
            new_name='id',
        ),
    ]
