# Generated by Django 3.2.4 on 2021-06-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_borrorer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrorer',
            new_name='borrower',
        ),
    ]
